name: Build APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK (Java Development Kit)
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # Alternatively, use 'adopt' or 'temurin'
        java-version: '17'   # Match the Java version your project uses

    # Step 3: Cache Gradle dependencies
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 4: Build the APK
    - name: Build APK
      run: ./gradlew assembleDebug

    # Step 5: Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk

